### PR TITLE
handle error in flatten:nextChunk()

### LINKED ISSUE #32: flatten ignores errors reported by individual streams in a stream of streams
Example Code

``` js
  pull(
    pull.values([
      pull.Source(function read(abort, cb) {
          cb(new Error('I am broken');)  
        })
    ]),
    pull.flatten(),
    pull.onEnd(function (err) {
      // err is null
    })
  )
```

### PR DESCRIPTION
**Pull request by regular**
Fixes #32

### CODE REVIEW

**Comment by dominictarr** [comment]
this looks right, but I think it needs to abort the parent stream too, before it calls back.

**Comment by regular** [comment]
yes. it is better, but not correct yet.

**Comment by regular** [comment]
@dominictarr Any thoughts on the new commits?

**Comment by dominictarr** [comment]
this looks great!
Merged into 2.28.4!

**Pull request merged**
