### PR TITLE
Fix aborting asyncMap while reading from async source

### PR DESCRIPTION
**Pull request by regular**
Hi Dominic,
we ran into this edge case yesterday and were able to fix it.
Have a nice day!
Jan

### CODE REVIEW

**Comment by dominictarr** [comment]
I get a test failure

```
# abort async map (async source)
ok 4 Abort's callback
not ok 5 plan != count
  ---
    operator: fail
    expected: 2
    actual:   1
    at: Immediate._onImmediate (/home/dominic/c/pull-stream/test/async-map.js:52:25)
  ...
ok 6 read's callback

```

I'm not sure this is correct - `abortCb` is only used if the async mapper is currently running. If it's just reading from the upstream, then should be able to call `read(abort)` without waiting.

But, your tests are correct. with my code, and your test, I still get the failure though.

**Comment by dominictarr** [comment]
Okay I cherry-picked your tests, but i fixed it a different way. https://github.com/dominictarr/pull-stream/commit/8e8bed8c073f9a820967f843c134158cb92d4b88

In this case, the source has been called with abort, but the previous read callback hasn't returned yet. this is a different case to what I covered before, where the mapper was running. solution is to check if the stream is aborted before running the mapper and if so callback immediately.

**Comment by regular** [comment]
Not sure why I thought the test would pass ... Reason for failing is the superfluous t.end() (making a false assumption about the order in which the two callbacks are being called). Now it passes.

**Comment by dominictarr** [comment]
that test was actually correct though. It should callback the non aborting read's callback first, then the abort callback. 

Okay, I checked the spec.md and fixed that https://github.com/dominictarr/pull-stream/commit/ba7f368b81bcbddeae02d80184c379d5c849a24b I only realized the need to abort during reads recently (okay maybe it's two years now) so some of the older streams don't do that especially (though many just work) and documentation wasn't fully up to date.

**Comment by regular** [comment]
Nice, 8e8bed8 fixes the problem we ran into. Would be great if you could publish it!

**Comment by dominictarr** [comment]
great, published in 3.3.1

**Pull request closed without merging**
