### PR TITLE
take shouldn't do abort inside a data read

### PR DESCRIPTION
**Pull request by dominictarr**
This change fixes problem mentioned here: https://github.com/dominictarr/pull-stream/issues/26#issuecomment-138457876

Don't abort the source stream unless you are gonna cb end. if it's data, you should wait for one more read to abort. This allows you to cb the error, if one occurs during the abort.

### CODE REVIEW

**Comment by dominictarr** [comment]
@regular this is what i'm thinking

**Comment by regular** [comment]
Yes, I see, that looks good. In an attempt to summarise (--verbosity=3):

### Rules for implementing `read` in a through stream:

#### 1) if called with `true` (meaning downstream, i.e. the sink has enough data)
  - just forward the exact `read()` call to the upstream chain to inform everyone.
  - switch to a new mode, where any attempt to `read()` is answered with `cb(true)`

#### 2) if instead _we_ have enough data
  - initiate an abort by calling `read(true)` (causing the aforementioned behaviour (1) upstream)
    - make sure to pass any potential `err` (failure during abort) down the downstream chain
    - if all goes well, `err` will just be the value `true`
    - both cases will cause the behaviour (3) described below downstream

#### 3) if, during a `read(null, cb)` from upstream (i.e. the Source), our callback is called with `err !== null` (meaning upstream, i.e. the Source, is either exhausted or has a problem)
  - forward that exact callback towards the downstream chain (towards Sink) to inform everybody.
  - switch to a new mode, where any attempt to `read()` is answered with `cb(err)`  (the `err` we received)

__In none of the above cases data is flowing!__

### 4) If data is flowing (normal operation: `read(null, cb)` causes `cb(null, data)`
  - forward `data` downstream (towards the Sink)
  - _do none of the above!_

_There either is data flowing (4) OR you have the error/abort cases (1-3), never both_.

Did I miss anything?

And now, excuse me, I have to go fix some code in `pull-generate` :)

**Comment by dominictarr** [comment]
yeah, that sounds about right. I got a bit confused in places though so i'm gonna merge this and add what you wrote (more or less) to the documentation.

**Comment by dominictarr** [comment]
merged into 2.28.2

**Pull request merged**
